import Navbar from "@/components/Navbar";
import "./globals.css";
import { JetBrains_Mono } from "next/font/google";

const JetBrains = JetBrains_Mono({
  weight:["400","800"],
  display:"swap",
  subsets:["latin"]
})

export const metadata = {
  title: "Yug",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${JetBrains.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
